### ISSUE TITLE
Wrong plugin directory?

### ISSUE THREAD

**Issue by rlipscombe** [legoscia/cautious-rotary-phone#1]
My plugins live in `~/.config/wireshark/plugins`, according to Help -> About -> Folders.

I'm running Wireshark 2.2.6, which is the default version for Ubuntu 16.04 (actually Mint 18.3).

Other than that, the dissectors appear to be working fine with the simple stuff I've tried so far :+1:

Edit: spoke too soon. See the other issues :)

**Comment by legoscia** [comment]
Good catch! Seems like this has varied a bit across versions, but that directory name should be stable. I updated the README, including the hint about the "About" dialog.
