### ISSUE TITLE
attempt to get length of field '?' (a nil value)

### ISSUE THREAD

**Issue by rlipscombe** [legoscia/cautious-rotary-phone#2]
Frame 12 in the attached.
[foo.trace.gz](https://github.com/legoscia/cautious-rotary-phone/files/2094069/foo.trace.gz)

**Comment by rlipscombe** [comment]
That file is also a bit ... crashy with my version of Wireshark. I'll upgrade and try again.

**Comment by ghost** [comment]
Can you provide steps to view the content of that file please.

**Comment by rlipscombe** [comment]
On bash, `gunzip foo.trace.gz` will give you `foo.trace`. Load that into Wireshark as if you'd captured it from an Erlang trace session.

**Comment by legoscia** [comment]
Thanks! This change seems to fix it.
